// Generates seed.sql from the authoritative wc2026_matches.json.
// Run with: npm run gen:seed   (node scripts/gen_seed.mjs)
//
// It emits: groups, 48 teams (with flagcdn ISO codes + FIFA rankings), all 104
// matches (group games resolved to team ids; knockout games keep their
// placeholder strings; finished games carry scores), and a separable optional
// DEMO DATA block (two auth users, a demo league, and the seeded predictions).
//
// Team id assignment is deterministic: groups A..L, in the confirmed-spec order
// within each group, ids 1..48.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const feed = JSON.parse(readFileSync(join(root, 'wc2026_matches.json'), 'utf8'))

// Official FIFA rankings (user-provided). team name -> fifa_global_rank.
const rankFile = JSON.parse(readFileSync(join(root, 'wc2026_fifa_rankings.json'), 'utf8'))
const FIFA_RANK = {}
for (const t of rankFile.teams) FIFA_RANK[t.team] = t.fifa_global_rank

// Confirmed group order (spec). Names MUST match the JSON's home/away strings.
const GROUPS = {
  A: ['Mexico', 'South Africa', 'Korea Republic', 'Czechia'],
  B: ['Canada', 'Bosnia & Herzegovina', 'Qatar', 'Switzerland'],
  C: ['Brazil', 'Morocco', 'Haiti', 'Scotland'],
  D: ['USA', 'Paraguay', 'Australia', 'Turkey'],
  E: ['Germany', 'Curaçao', "Côte d'Ivoire", 'Ecuador'],
  F: ['Netherlands', 'Japan', 'Sweden', 'Tunisia'],
  G: ['Belgium', 'Egypt', 'Iran', 'New Zealand'],
  H: ['Spain', 'Cabo Verde', 'Saudi Arabia', 'Uruguay'],
  I: ['France', 'Senegal', 'Iraq', 'Norway'],
  J: ['Argentina', 'Algeria', 'Austria', 'Jordan'],
  K: ['Portugal', 'DR Congo', 'Uzbekistan', 'Colombia'],
  L: ['England', 'Croatia', 'Ghana', 'Panama']
}

// flagcdn ISO codes (gb-eng / gb-sct for the UK constituents) + short code +
// an approximate FIFA ranking (June 2026 snapshot — admin-editable; used only
// as the LAST tiebreaker. Verify against the official list if it ever matters).
const TEAM_META = {
  Mexico: ['mx', 'MEX', 14], 'South Africa': ['za', 'RSA', 58], 'Korea Republic': ['kr', 'KOR', 23], Czechia: ['cz', 'CZE', 40],
  Canada: ['ca', 'CAN', 30], 'Bosnia & Herzegovina': ['ba', 'BIH', 74], Qatar: ['qa', 'QAT', 53], Switzerland: ['ch', 'SUI', 20],
  Brazil: ['br', 'BRA', 5], Morocco: ['ma', 'MAR', 12], Haiti: ['ht', 'HAI', 83], Scotland: ['gb-sct', 'SCO', 39],
  USA: ['us', 'USA', 16], Paraguay: ['py', 'PAR', 41], Australia: ['au', 'AUS', 26], Turkey: ['tr', 'TUR', 27],
  Germany: ['de', 'GER', 9], 'Curaçao': ['cw', 'CUW', 82], "Côte d'Ivoire": ['ci', 'CIV', 42], Ecuador: ['ec', 'ECU', 31],
  Netherlands: ['nl', 'NED', 7], Japan: ['jp', 'JPN', 17], Sweden: ['se', 'SWE', 36], Tunisia: ['tn', 'TUN', 49],
  Belgium: ['be', 'BEL', 8], Egypt: ['eg', 'EGY', 33], Iran: ['ir', 'IRN', 21], 'New Zealand': ['nz', 'NZL', 86],
  Spain: ['es', 'ESP', 2], 'Cabo Verde': ['cv', 'CPV', 70], 'Saudi Arabia': ['sa', 'KSA', 60], Uruguay: ['uy', 'URU', 15],
  France: ['fr', 'FRA', 3], Senegal: ['sn', 'SEN', 18], Iraq: ['iq', 'IRQ', 58], Norway: ['no', 'NOR', 32],
  Argentina: ['ar', 'ARG', 1], Algeria: ['dz', 'ALG', 37], Austria: ['at', 'AUT', 22], Jordan: ['jo', 'JOR', 62],
  Portugal: ['pt', 'POR', 6], 'DR Congo': ['cd', 'COD', 56], Uzbekistan: ['uz', 'UZB', 57], Colombia: ['co', 'COL', 13],
  England: ['gb-eng', 'ENG', 4], Croatia: ['hr', 'CRO', 10], Ghana: ['gh', 'GHA', 73], Panama: ['pa', 'PAN', 43]
}

// Assign ids 1..48
const teamId = {}
const teamRows = []
let id = 0
for (const g of Object.keys(GROUPS)) {
  for (const name of GROUPS[g]) {
    id += 1
    teamId[name] = id
    const meta = TEAM_META[name]
    if (!meta) throw new Error('Missing TEAM_META for ' + name)
    teamRows.push({ id, name, code: meta[1], flag: meta[0], group: g, rank: meta[2] })
  }
}

const sq = (s) => (s === null || s === undefined ? 'null' : "'" + String(s).replace(/'/g, "''") + "'")
const num = (n) => (n === null || n === undefined ? 'null' : String(n))

let out = ''
out += '-- ============================================================================\n'
out += '-- SEED DATA — generated by scripts/gen_seed.mjs from wc2026_matches.json\n'
out += '-- Run AFTER schema.sql. Do not hand-edit; re-run the generator instead.\n'
out += '-- ============================================================================\n\n'

// Admin email config placeholder
out += "-- Set this to YOUR admin email (must match VITE_ADMIN_EMAIL in .env).\n"
// Insert config defaults but NEVER clobber values the admin has already set
// (so re-running seed.sql is safe after you change the admin email / lock).
out += "insert into public.app_config (key, value) values\n"
out += "  ('admin_email', 'admin@worldcup.com'),\n"
out += "  ('pretournament_manual_lock', 'false'),\n"
out += "  ('accumulate_advance', 'false')\n"
out += "on conflict (key) do nothing;\n\n"

// Groups
out += 'insert into public.groups (letter) values\n'
out += Object.keys(GROUPS).map((g) => `  ('${g}')`).join(',\n') + '\non conflict do nothing;\n\n'

// Teams
// fifa_ranking from the official wc2026_fifa_rankings.json (fifa_global_rank).
out += 'insert into public.teams (id, name, code, flag_code, group_letter, fifa_ranking) values\n'
out += teamRows
  .map((t) => {
    const rk = FIFA_RANK[t.name]
    if (rk == null) throw new Error('No FIFA rank for ' + t.name)
    return `  (${t.id}, ${sq(t.name)}, ${sq(t.code)}, ${sq(t.flag)}, '${t.group}', ${rk})`
  })
  .join(',\n')
out += '\non conflict (id) do update set name=excluded.name, code=excluded.code, flag_code=excluded.flag_code, group_letter=excluded.group_letter, fifa_ranking=excluded.fifa_ranking;\n\n'

// Matches
const matchRows = []
for (const m of feed.matches) {
  const isGroup = m.stage === 'group'
  const homeId = isGroup ? teamId[m.home] : null
  const awayId = isGroup ? teamId[m.away] : null
  const homePh = isGroup ? null : m.home
  const awayPh = isGroup ? null : m.away
  if (isGroup && (!homeId || !awayId)) {
    throw new Error(`Unmapped group team in match ${m.match_no}: ${m.home} / ${m.away}`)
  }
  const fin = m.score && m.score.status === 'finished'
  const hs = fin ? m.score.ft[0] : null
  const as = fin ? m.score.ft[1] : null
  const status = fin ? 'finished' : 'scheduled'
  const thirdPlace = m.stage === 'third_place'
  matchRows.push(
    `  (${m.match_no}, ${m.match_no}, ${sq(m.stage)}, ${sq(m.round)}, ${m.group ? sq(m.group) : 'null'}, ` +
      `${num(homeId)}, ${num(awayId)}, ${sq(homePh)}, ${sq(awayPh)}, ` +
      `'${m.kickoff_utc}'::timestamptz, ${sq(m.venue)}, ${num(hs)}, ${num(as)}, ${thirdPlace}, ${sq(status)})`
  )
}
out += 'insert into public.matches\n'
out += '  (id, match_no, stage, round, group_letter, home_team_id, away_team_id, home_placeholder, away_placeholder, kickoff_utc, venue, home_score, away_score, is_third_place_playoff, status) values\n'
out += matchRows.join(',\n')
out += '\non conflict (id) do update set\n'
out += '  stage=excluded.stage, round=excluded.round, group_letter=excluded.group_letter,\n'
out += '  home_team_id=excluded.home_team_id, away_team_id=excluded.away_team_id,\n'
out += '  home_placeholder=excluded.home_placeholder, away_placeholder=excluded.away_placeholder,\n'
out += '  kickoff_utc=excluded.kickoff_utc, venue=excluded.venue,\n'
out += '  home_score=excluded.home_score, away_score=excluded.away_score,\n'
out += '  is_third_place_playoff=excluded.is_third_place_playoff, status=excluded.status;\n\n'

// ---------------------------------------------------------------------------
// DEMO DATA (optional). Comment out this whole block for a clean prod seed.
// ---------------------------------------------------------------------------
const PRIYANKA = '11111111-1111-1111-1111-111111111111'
const ROHIT = '22222222-2222-2222-2222-222222222222'
const LEAGUE = '33333333-3333-3333-3333-333333333333'
const ADMIN = '44444444-4444-4444-4444-444444444444'

// match_no per (group, homeName, awayName) for resolving seeded predictions.
const groupMatchByPair = {}
for (const m of feed.matches) {
  if (m.stage === 'group') groupMatchByPair[`${m.group}|${m.home}|${m.away}`] = m.match_no
}
// Seeded predictions exactly as written. Each: [group, home, away, hp, ap].
const PRIYANKA_PREDS = [
  ['A', 'Mexico', 'South Africa', 3, 2],
  ['A', 'Korea Republic', 'Czechia', 4, 2],
  ['B', 'Canada', 'Bosnia & Herzegovina', 1, 0],
  ['D', 'USA', 'Paraguay', 2, 2],
  ['B', 'Qatar', 'Switzerland', 1, 2],
  ['C', 'Brazil', 'Morocco', 1, 2],
  ['C', 'Haiti', 'Scotland', 0, 2],
  ['D', 'Australia', 'Turkey', 1, 0],
  ['E', 'Germany', 'Curaçao', 2, 0]
]
const ROHIT_PREDS = [
  ['A', 'Mexico', 'South Africa', 2, 0],
  ['A', 'Korea Republic', 'Czechia', 1, 0],
  ['B', 'Canada', 'Bosnia & Herzegovina', 2, 0],
  ['D', 'USA', 'Paraguay', 2, 0],
  ['B', 'Qatar', 'Switzerland', 0, 3],
  // Brazil 2-1 Switzerland -> different groups -> UNMATCHED (skipped; see README)
  ['C', 'Haiti', 'Scotland', 0, 1],
  ['D', 'Australia', 'Turkey', 0, 2],
  ['E', 'Germany', 'Curaçao', 3, 0]
]

function resolvePreds(preds) {
  const rows = []
  const unmatched = []
  for (const [g, h, a, hp, ap] of preds) {
    const mn = groupMatchByPair[`${g}|${h}|${a}`]
    if (!mn) { unmatched.push(`${h} ${hp}-${ap} ${a} (Group ${g})`); continue }
    rows.push({ mn, hp, ap })
  }
  return { rows, unmatched }
}
const pr = resolvePreds(PRIYANKA_PREDS)
const ro = resolvePreds(ROHIT_PREDS)

out += '-- ===========================================================================\n'
out += '-- DEMO DATA (optional) — two players (Priyanka, Rohit) + a demo league.\n'
out += "-- Logins (password 'Worldcup123'): priyanka@ / rohit@ / admin@worldcup.com. Delete this block for a clean seed.\n"
out += '-- ===========================================================================\n'
out += 'do $$\nbegin\n'
for (const [uid, email, name] of [
  [PRIYANKA, 'priyanka@worldcup.com', 'Priyanka'],
  [ROHIT, 'rohit@worldcup.com', 'Rohit'],
  [ADMIN, 'admin@worldcup.com', 'Admin']
]) {
  out += `  insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, confirmation_token, recovery_token, email_change_token_new, email_change)\n`
  out += `  values ('${uid}', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '${email}', crypt('Worldcup123', gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{"display_name":"${name}"}', '', '', '', '')\n`
  out += `  on conflict (id) do nothing;\n`
  out += `  insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)\n`
  out += `  values (gen_random_uuid(), '${uid}', '${uid}', json_build_object('sub','${uid}','email','${email}'), 'email', now(), now(), now())\n`
  out += `  on conflict do nothing;\n`
}
out += 'end $$;\n\n'

out += "insert into public.profiles (id, email, display_name) values\n"
out += `  ('${PRIYANKA}', 'priyanka@worldcup.com', 'Priyanka'),\n`
out += `  ('${ROHIT}', 'rohit@worldcup.com', 'Rohit'),\n`
out += `  ('${ADMIN}', 'admin@worldcup.com', 'Admin')\n`
out += 'on conflict (id) do update set display_name = excluded.display_name;\n\n'

out += "insert into public.leagues (id, name, invite_code, owner_id) values\n"
out += `  ('${LEAGUE}', 'Demo League', 'DEMO26', '${PRIYANKA}')\non conflict (id) do nothing;\n\n`

out += 'insert into public.league_members (league_id, user_id) values\n'
out += `  ('${LEAGUE}', '${PRIYANKA}'),\n  ('${LEAGUE}', '${ROHIT}')\non conflict do nothing;\n\n`

function predInserts(uid, rows) {
  let s = 'insert into public.predictions (league_id, user_id, match_id, home_pred, away_pred) values\n'
  s += rows.map((r) => `  ('${LEAGUE}', '${uid}', ${r.mn}, ${r.hp}, ${r.ap})`).join(',\n')
  s += '\non conflict (league_id, user_id, match_id) do update set home_pred=excluded.home_pred, away_pred=excluded.away_pred;\n\n'
  return s
}
out += predInserts(PRIYANKA, pr.rows)
out += predInserts(ROHIT, ro.rows)

out += '-- Unmatched seeded predictions (skipped — see README):\n'
for (const u of [...pr.unmatched, ...ro.unmatched]) out += `--   Rohit/Priyanka: ${u}\n`
out += '\n'

writeFileSync(join(root, 'seed.sql'), out)
console.log(`seed.sql written: ${teamRows.length} teams, ${matchRows.length} matches.`)
console.log(`Priyanka preds: ${pr.rows.length}, unmatched: ${pr.unmatched.length}`)
console.log(`Rohit preds: ${ro.rows.length}, unmatched: ${JSON.stringify(ro.unmatched)}`)
